// Extracts the operation catalogue from the vendored Specification's operation tables and
// writes data/operations.yaml (project spec section 8.2, risk R4).
//
//   npx tsx tools/extract-operations.ts
//
// Every operation table becomes one signature; operations defined for several types (for
// example math/eq for float, int and bool) get several signatures. Each signature records the
// Specification line it came from. Special-case rows of the definition tables are added by
// hand in a later milestone; this tool records only what the tables state.

import { readFileSync, writeFileSync } from 'node:fs';
import { stringify } from 'yaml';
import { parseOperationTables, SPEC_REVISION } from '../src/registry/specTables.js';

const specPath = new URL('../data/spec/Specification.adoc', import.meta.url);
const outPath = new URL('../data/operations.yaml', import.meta.url);

const catalogue = parseOperationTables(readFileSync(specPath, 'utf8'));
const header = [
  '# Operation catalogue extracted from the KHR_interactivity Specification.',
  `# Source: data/spec/Specification.adoc (glTF revision ${SPEC_REVISION}).`,
  '# Generated by tools/extract-operations.ts; do not edit by hand. Re-run the tool instead.',
  '',
].join('\n');
writeFileSync(outPath, header + stringify(catalogue, { lineWidth: 0 }), 'utf8');
process.stdout.write(
  `${catalogue.operations.length} operations, ${catalogue.operations.reduce((n, o) => n + o.signatures.length, 0)} signatures\n`,
);
